# Jekyll
permalink: /:year/:title/

# post.url will be added to the end to get a shareable permalink
url: http://zduck.com

email: joshua@zduck.com

exclude: ['withdrawn/**', 'drafts/**']

markdown: redcarpet

powershell_book_ad: |
    <blockquote>
    <div style="float: left; padding-right: 10px;">
    <a href="http://www.amazon.com/gp/product/1935182137/ref=as_li_ss_il?ie=UTF8&camp=1789&creative=390957&creativeASIN=1935182137&linkCode=as2&tag=zduck-20"><img border="0" src="http://ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=1935182137&Format=_SL110_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=zduck-20" ></a><img src="http://ir-na.amazon-adsystem.com/e/ir?t=zduck-20&l=as2&o=1&a=1935182137" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
    </div>
    <p>Want to learn PowerShell? Check out <a href="http://www.amazon.com/gp/product/1935182137/ref=as_li_ss_il?ie=UTF8&camp=1789&creative=390957&creativeASIN=1935182137&linkCode=as2&tag=zduck-20">Windows PowerShell in Action</a> by Bruce Payette. This is the book that got me started and it's one of the best tech books I've read.</p>
    <div style="clear: both;" />
    </blockquote>

go_101_blurb: |
    <blockquote style="text-style: italic;">
    <p>
        Go 101 is a series of short posts
        to help familiarize new users with the "way to Go".
        Topics will answer questions that a programmer
        experienced in another object-oriented language (e.g. C#)
        might have when they start using Go.
    </p>
    <ul>
        <li><a href="/2014/go-conventions-constructors-and-overloads">Constructors and Overloads</a></li>
        <li><a href="/2014/go-101-methods-on-pointers-vs-values">Methods on Pointers vs. Values</a></li>
        <li><a href="/2014/go-101-string-or-byte-slice">String or Byte Slice?</a></li>
    </ul>
    <p style="text-style: italic;">
        Read up on <a href="http://golang.org/doc/effective_go.html">Effective Go</a>
        and the <a href="http://golang.org/doc/faq">Go FAQ</a> to learn all of this and more.
    </p>
    </blockquote>