# Jekyll
permalink: /:year/:title/

# post.url will be added to the end to get a shareable permalink
url: http://localhost:4000

email: joshua@zduck.com

exclude: ['withdrawn/**', 'drafts/**']

markdown: redcarpet